spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
        - AddRequestHeader=proxied, true
      routes:
        - id: resource
          uri: http://localhost:10000
          predicates:
            - Path=/resource/**

        - id: login
          uri: http://localhost:10002
          predicates:
            - Path=/auth/auth/**

endpoints:
  opened:
    - /auth/login

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    health:
      enabled: true
      show-details: always
    web:
      exposure:
        include: health, prometheus
    metrics:
      export:
        prometheus:
          enabled: true